# Generated by Django 4.2.4 on 2023-10-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20, verbose_name='プレイヤ名')),
                ('player_rate', models.IntegerField(verbose_name='レート')),
                ('userWinningStreak', models.IntegerField(verbose_name='連勝数')),
                ('achieved_at', models.DateTimeField(auto_now_add=True, verbose_name='達成日時')),
            ],
            options={
                'verbose_name_plural': 'レート',
            },
        ),
    ]
